Add some variables to make the module idempotent
onetwopunch/terraform-vault-okta pull request #3
Opened 2021-03-30 09:22 UTC by flamein

I've added 3 variables that are being set by vault by default, but cause a change with regard to terraform state.

It prevents a situation like this on subsequent runs:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.okta.vault_jwt_auth_backend.okta_oidc will be updated in-place
  ~ resource "vault_jwt_auth_backend" "okta_oidc" {
        id                     = "okta_oidc"
      ~ tune                   = [
          + {
              + allowed_response_headers     = []
              + audit_non_hmac_request_keys  = []
              + audit_non_hmac_response_keys = []
              + default_lease_ttl            = ""
              + listing_visibility           = "unauth"
              + max_lease_ttl                = ""
              + passthrough_request_headers  = []
              + token_type                   = ""
            },
          - {
              - allowed_response_headers     = []
              - audit_non_hmac_request_keys  = []
              - audit_non_hmac_response_keys = []
              - default_lease_ttl            = "768h"
              - listing_visibility           = "unauth"
              - max_lease_ttl                = "768h"
              - passthrough_request_headers  = []
              - token_type                   = "default-service"
            },
        ]
        # (11 unchanged attributes hidden)
    }
```

I regenerated the docs, it seems the format changed a bit since the last time it was used in this repository, but fixing that might be beyond the scope of this PR...

2021-04-23 12:23 UTC, flamein commented
@onetwopunch: how do you feel about this change?

2021-04-23 16:24 UTC, onetwopunch requested changes
Terribly sorry for the slow response on this, I must have missed the notification. I'm not sure what method you're using for generating docs, but lets keep things simple and just copy/paste the output from `terraform-docs markdown .` into the README. 

Otherwise, the changed LGTM.

2021-04-26 07:38 UTC, flamein commented
I used the script provided in scripts/docs.sh, let's see what terraform-docs markdown . gives

2021-04-26 07:46 UTC, flamein commented
Apparently the output format of `terraform-docs markdown .` changed since you last generated the docs.
I can just add the parts that describe the change I made to keep this PR clean

2021-04-27 02:20 UTC, onetwopunch approved these changes
Weird, I'll have to make a PR to update the docs. Thanks for the PR!

2021-04-27 02:24 UTC, merged